# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Dr. Atreya Acharyya PhD AFHEA"
title_separator          : "-"
name                     : &name "Atreya Acharyya"
description              : &description "Astrophysicist specializing in gamma-ray astronomy, AGN, and multi-messenger astrophysics"
url                      : "https://atreyaacharyya.github.io"
baseurl                  : ""
repository               : "atreyaacharyya/atreyaacharyya.github.com"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Atreya Acharyya"
  pronouns         :
  bio              : "Astrophysicist working on gamma-ray astronomy, AGN, and multi-messenger astrophysics."
  location         : "Odense, Denmark"
  employer         : "University of Southern Denmark"
  uri              :
  email            : "atreya@cp3.sdu.dk"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0000-0002-2028-9230"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "atreyaacharyya"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "atreya-acharyya-95b652a9"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
